--- # thi is dir file
- hosts: webservers
  connection: ssh
  user: ansible
  become: yes

  tasks:
    - name: creating a directory
      file:
        path: /home/ansible/abc123xyz
        state: touch
