--- #
- hosts: webservers
  become: yes


  tasks:
    - name: install java
      yum:
        name: java
        state: present
      when: ansible_os_family == "RedHat"


    - name: install java on debian
      apt:
        name: java
        state: present
      when: ansible_os_family == "Debian"

    - name: download tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.9/bin/apache-tomcat-10.1.9.tar.gz
        dest: /opt



    - name: extract tomcat s/w
      unarchive: 
        src: /opt/apache-tomcat-10.1.9.tar.gz
        dest: /opt
        remote_src: yes


    - name: provinding excutable permission
      file:
        path: /opt/apache-tomcat-10.1.9/bin/startup.sh
        mode: 0777



    - name: start the service of tomcat
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-10.1.9/bin
