--- #
- hosts: webservers
  become: yes
  user: ansible
  connection: ssh

  vars:
    pkgname: httpd


  tasks:
    - name: instal httpd on servers
      action: yum name='{{pkgname}}' state=installed 
